//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA47Team07AProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities : DbContext
    {
        public LibraryEntities()
            : base("name=LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MemberCategory> MemberCategories { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<ReceiptView> ReceiptView { get; set; }
        public virtual DbSet<MemberListView> MemberListView { get; set; }
        public virtual DbSet<ListOfBooksOnLoan> ListOfBooksOnLoan { get; set; }
        public virtual DbSet<ManagementView> ManagementView { get; set; }
    }
}
