//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA47Team07AProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagementView
    {
        public int BookID { get; set; }
        public string BookName { get; set; }
        public int RecordID { get; set; }
        public string Status { get; set; }
    }
}
