//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA47Team07AProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberListView
    {
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public string MemberCategory { get; set; }
        public string CategoryName { get; set; }
        public short TotalBorrowBooks { get; set; }
        public short CurrentBorrowBooks { get; set; }
    }
}
