//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA47Team07AProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int RecordID { get; set; }
        public int MemberID { get; set; }
        public int StaffID { get; set; }
        public int BookID { get; set; }
        public System.DateTime BorrowDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Member Member { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
